name: invest_app
description: A new Flutter investment application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # <--- PASTIKAN INDENTASI INI BENAR (2 spasi dari 'dependencies:')
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  url_launcher: ^6.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png "

flutter:
  uses-material-design: true
  generate: true # <--- PASTIKAN BARIS INI ADA DAN INDENTASINYA BENAR (2 spasi dari 'flutter:')

  assets:
    - assets/images/cryptocurrency.png
    - assets/images/app_logo.png # Jika Anda memiliki file ini, pastikan ada
